### ISSUE TITLE
[feature request]possibility of retrieving rbac rules via promise

### ISSUE THREAD

**Issue by gitawego** [franciscogouveia/hapi-rbac#12]
firstly, thanks for your great plugin, it's the most flexible authorization plugin for hapijs. 
but I'd like to be able to store the rbac setting in database and retrieve them via a promise, so admin can dynamically change the rules without restarting the server. 
I think the simple way is to detect if ``request.route.settings.plugins.rbac`` a function, if yes, execute it and get a promise.

thanks in advance

**Comment by franciscogouveia** [comment]
I agree that this feature would be great and I like your suggestion of accepting a function on the rbac configuration. I would use a normal callback function instead of a promise though.

I will look into it.

**Comment by franciscogouveia** [comment]
@gitawego Can you please check if it covers your case?

**Comment by gitawego** [comment]
yes, it seems promising, I'm gonna test tonight. thanks a lot :)

**Comment by franciscogouveia** [comment]
You are welcome :) I will close the issue
