### ISSUE TITLE
Extract core

### ISSUE THREAD

**Issue by deedubs** [franciscogouveia/hapi-rbac#20]
We have a use case where we would like to be able to use RBACs at a deeper layer then hapi/http. Would you be open to extracting the core functionality into a lib?

I'll be able to help on the PR.

**Comment by franciscogouveia** [comment]
I had this same idea last week, it makes perfect sense. I don't mind taking care of it.

**Comment by franciscogouveia** [comment]
You can use the core named `rbac-core` ([npm](https://www.npmjs.com/package/rbac-core), [github](https://github.com/franciscogouveia/rbac-core)).

Check how to use it in the tests.

**Comment by ovaillancourt** [comment]
@franciscogouveia Wow man props for the super-quick turnaround on this! Thanks :D.

**Comment by franciscogouveia** [comment]
You are welcome :+1: I will close the issue now. Create a new one if questions arise.
