### ISSUE TITLE
Method of defining Role hierarchy?

### ISSUE THREAD

**Issue by zolrath** [franciscogouveia/hapi-rbac#4]
In the case of having roles such as ADMIN, MANAGER, REP, USER while defining the lower tier of rules
for a User in this case:
```javascript
{
	target: ['any-of',
		{type: "role", value: "ADMIN"},
		{type: "role", value: "MANAGER"},
		{type: "role", value: "REP"},
		{type: "role", value: "USER"},
	],
	effect: 'permit'	
}
```
it appears that I must do an 'any-of' and supply every more privileged role in the rule.
Is there a method of defining that ADMIN > MANAGER > REP > USER, allowing something akin to a greater-than or equal to rule ```type: "role", gte: "USER"```

**Comment by franciscogouveia** [comment]
This rbac plugin, as it is now, has no knowledge on data. It means that it is not possible to infer hierarchies.

But, you can play with the rules/effects. If you want to grant access to:

(1) All except USER, then:

```
{
    target: ['any-of',
        {type: "role", value: "USER"}
    ],
    effect: 'deny'
}
```

(2) All, except USER and REP:

```
{
    target: ['any-of',
        {type: "role", value: "USER"},
        {type: "role", value: "REP"}
    ],
    effect: 'deny'
}
```

Only ADMIN and MANAGER (same as 2, in this case):

```
{
    target: ['any-of',
        {type: "role", value: "ADMIN"},
        {type: "role", value: "MANAGER"}
    ],
    effect: 'permit'
}
```
